baseURL = "https://blog.selcukcihan.com/"
languageCode = "tr-TR"
title = "Yazılım ile ilgili notlar"
theme = "ezhil"
DefaultContentLanguage = "tr"
copyright = "© Selçuk Cihan"

# Enable syntax highlighting.
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = "UA-68700480-6"
# Your Disqus sortname.
disqusShortname = "blog-selcukcihan-com"

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "Çözdüğüm problemleri ve bu yolda öğrendiklerimi yazıyorum. - *\"Söz uçar, yazı kalır\"*"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    favicon = "/icons/favicon-16x16.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    mode = "dark" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    # customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`.
    # customJS = ["js/abc.js", "js/xyz.js"]


# Main menu which appears below site header.
[[menu.main]]
name = "Ana sayfa"
url = "/"
weight = 1

[[menu.main]]
name = "Tüm yazılar"
url = "/posts"
weight = 2

[[menu.main]]
name = "Etiketler"
url = "/tags"
weight = 3

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/selcukcihan"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/scihan"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://linkedin.com/in/selcukcihan"


# Enable tags.
[taxonomies]
   tag = "tags"
